// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpiNjthVqidlto0HyheGlBAQGKactl0uM',
    appId: '1:515721143660:web:c1efc39bb621827d00bf49',
    messagingSenderId: '515721143660',
    projectId: 'sweet-a',
    authDomain: 'sweet-a.firebaseapp.com',
    storageBucket: 'sweet-a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB25iDO_U6HEUdMit3zBt2HdqjSKG2Y_4M',
    appId: '1:515721143660:android:cf0e8b027a9d0d3d00bf49',
    messagingSenderId: '515721143660',
    projectId: 'sweet-a',
    storageBucket: 'sweet-a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1-aAeeBVweHcTbb2-ohHXB0VeeqkYPZI',
    appId: '1:515721143660:ios:acc821ba5437fa4e00bf49',
    messagingSenderId: '515721143660',
    projectId: 'sweet-a',
    storageBucket: 'sweet-a.appspot.com',
    iosBundleId: 'com.example.sweetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1-aAeeBVweHcTbb2-ohHXB0VeeqkYPZI',
    appId: '1:515721143660:ios:317c0ca2fee231d700bf49',
    messagingSenderId: '515721143660',
    projectId: 'sweet-a',
    storageBucket: 'sweet-a.appspot.com',
    iosBundleId: 'com.example.sweetApp.RunnerTests',
  );
}
